package rk.device.launcher.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import rk.device.launcher.db.entity.Authorization;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AUTHORIZATION".
*/
public class AuthorizationDao extends AbstractDao<Authorization, Long> {

    public static final String TABLENAME = "AUTHORIZATION";

    /**
     * Properties of entity Authorization.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FaceID = new Property(1, String.class, "faceID", false, "FACE_ID");
        public final static Property Info = new Property(2, String.class, "info", false, "INFO");
    }


    public AuthorizationDao(DaoConfig config) {
        super(config);
    }
    
    public AuthorizationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUTHORIZATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FACE_ID\" TEXT NOT NULL ," + // 1: faceID
                "\"INFO\" TEXT NOT NULL );"); // 2: info
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUTHORIZATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Authorization entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFaceID());
        stmt.bindString(3, entity.getInfo());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Authorization entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFaceID());
        stmt.bindString(3, entity.getInfo());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Authorization readEntity(Cursor cursor, int offset) {
        Authorization entity = new Authorization( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // faceID
            cursor.getString(offset + 2) // info
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Authorization entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFaceID(cursor.getString(offset + 1));
        entity.setInfo(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Authorization entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Authorization entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Authorization entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
