package rk.device.launcher.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import rk.device.launcher.db.entity.User;
import rk.device.launcher.db.entity.Record;

import rk.device.launcher.db.dao.UserDao;
import rk.device.launcher.db.dao.RecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig recordDaoConfig;

    private final UserDao userDao;
    private final RecordDao recordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Record.class, recordDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

}
