package rk.device.launcher.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import rk.device.launcher.db.entity.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UniqueId = new Property(1, String.class, "uniqueId", false, "UNIQUE_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property PopedomType = new Property(3, String.class, "popedomType", false, "POPEDOM_TYPE");
        public final static Property CardNo = new Property(4, String.class, "cardNo", false, "CARD_NO");
        public final static Property FingerID1 = new Property(5, String.class, "fingerID1", false, "FINGER_ID1");
        public final static Property FingerID2 = new Property(6, String.class, "fingerID2", false, "FINGER_ID2");
        public final static Property FingerID3 = new Property(7, String.class, "fingerID3", false, "FINGER_ID3");
        public final static Property FaceID = new Property(8, String.class, "faceID", false, "FACE_ID");
        public final static Property PassWord = new Property(9, int.class, "passWord", false, "PASS_WORD");
        public final static Property StartTime = new Property(10, long.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(11, long.class, "endTime", false, "END_TIME");
        public final static Property FingerCode = new Property(12, String.class, "fingerCode", false, "FINGER_CODE");
        public final static Property UploadStatus = new Property(13, int.class, "uploadStatus", false, "UPLOAD_STATUS");
        public final static Property CreateTime = new Property(14, long.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(15, long.class, "updateTime", false, "UPDATE_TIME");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UNIQUE_ID\" TEXT NOT NULL ," + // 1: uniqueId
                "\"NAME\" TEXT NOT NULL ," + // 2: name
                "\"POPEDOM_TYPE\" TEXT NOT NULL ," + // 3: popedomType
                "\"CARD_NO\" TEXT," + // 4: cardNo
                "\"FINGER_ID1\" TEXT," + // 5: fingerID1
                "\"FINGER_ID2\" TEXT," + // 6: fingerID2
                "\"FINGER_ID3\" TEXT," + // 7: fingerID3
                "\"FACE_ID\" TEXT," + // 8: faceID
                "\"PASS_WORD\" INTEGER NOT NULL ," + // 9: passWord
                "\"START_TIME\" INTEGER NOT NULL ," + // 10: startTime
                "\"END_TIME\" INTEGER NOT NULL ," + // 11: endTime
                "\"FINGER_CODE\" TEXT," + // 12: fingerCode
                "\"UPLOAD_STATUS\" INTEGER NOT NULL ," + // 13: uploadStatus
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 14: createTime
                "\"UPDATE_TIME\" INTEGER NOT NULL );"); // 15: updateTime
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_USER_UNIQUE_ID ON \"USER\"" +
                " (\"UNIQUE_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUniqueId());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getPopedomType());
 
        String cardNo = entity.getCardNo();
        if (cardNo != null) {
            stmt.bindString(5, cardNo);
        }
 
        String fingerID1 = entity.getFingerID1();
        if (fingerID1 != null) {
            stmt.bindString(6, fingerID1);
        }
 
        String fingerID2 = entity.getFingerID2();
        if (fingerID2 != null) {
            stmt.bindString(7, fingerID2);
        }
 
        String fingerID3 = entity.getFingerID3();
        if (fingerID3 != null) {
            stmt.bindString(8, fingerID3);
        }
 
        String faceID = entity.getFaceID();
        if (faceID != null) {
            stmt.bindString(9, faceID);
        }
        stmt.bindLong(10, entity.getPassWord());
        stmt.bindLong(11, entity.getStartTime());
        stmt.bindLong(12, entity.getEndTime());
 
        String fingerCode = entity.getFingerCode();
        if (fingerCode != null) {
            stmt.bindString(13, fingerCode);
        }
        stmt.bindLong(14, entity.getUploadStatus());
        stmt.bindLong(15, entity.getCreateTime());
        stmt.bindLong(16, entity.getUpdateTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUniqueId());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getPopedomType());
 
        String cardNo = entity.getCardNo();
        if (cardNo != null) {
            stmt.bindString(5, cardNo);
        }
 
        String fingerID1 = entity.getFingerID1();
        if (fingerID1 != null) {
            stmt.bindString(6, fingerID1);
        }
 
        String fingerID2 = entity.getFingerID2();
        if (fingerID2 != null) {
            stmt.bindString(7, fingerID2);
        }
 
        String fingerID3 = entity.getFingerID3();
        if (fingerID3 != null) {
            stmt.bindString(8, fingerID3);
        }
 
        String faceID = entity.getFaceID();
        if (faceID != null) {
            stmt.bindString(9, faceID);
        }
        stmt.bindLong(10, entity.getPassWord());
        stmt.bindLong(11, entity.getStartTime());
        stmt.bindLong(12, entity.getEndTime());
 
        String fingerCode = entity.getFingerCode();
        if (fingerCode != null) {
            stmt.bindString(13, fingerCode);
        }
        stmt.bindLong(14, entity.getUploadStatus());
        stmt.bindLong(15, entity.getCreateTime());
        stmt.bindLong(16, entity.getUpdateTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // uniqueId
            cursor.getString(offset + 2), // name
            cursor.getString(offset + 3), // popedomType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // cardNo
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // fingerID1
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // fingerID2
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // fingerID3
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // faceID
            cursor.getInt(offset + 9), // passWord
            cursor.getLong(offset + 10), // startTime
            cursor.getLong(offset + 11), // endTime
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // fingerCode
            cursor.getInt(offset + 13), // uploadStatus
            cursor.getLong(offset + 14), // createTime
            cursor.getLong(offset + 15) // updateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUniqueId(cursor.getString(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setPopedomType(cursor.getString(offset + 3));
        entity.setCardNo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFingerID1(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFingerID2(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFingerID3(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFaceID(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPassWord(cursor.getInt(offset + 9));
        entity.setStartTime(cursor.getLong(offset + 10));
        entity.setEndTime(cursor.getLong(offset + 11));
        entity.setFingerCode(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setUploadStatus(cursor.getInt(offset + 13));
        entity.setCreateTime(cursor.getLong(offset + 14));
        entity.setUpdateTime(cursor.getLong(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
